remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

title: "JSON Compare"
tagline: "Compare and match JSONs in Java, with regex and JSONPath support"
description: "Java library for comparing and matching JSONs and any JSON convertible Java objects, with regex, JSONPath and embedded match operators; reports every difference when the assertion fails"
author: "Florin Slevoaca"
url: "https://fslev.github.io/json-compare"
permalink: pretty
google_analytics: G-T93JGK4KGJ
